### ISSUE TITLE
No TypeHinting

### ISSUE THREAD

**Issue by Kapsonfire** [swoole/ide-helper#19]
The docs are missing typehints in phpdoc

Like in Coroutine\Mysql -> prepare()

`/**
     * @return \Swoole\Coroutine\MySQL\Statement
     */
    public function prepare($query, $timeout = null)
    {
    }`

**Comment by deminy** [comment]
The stubs are created by reverse-engineering the Swoole extensions directly; thus there is no documentation included, and type hinting is missing in many places. The Swoole team has tried its best to keep the stubs up to date, and we do want to add inline documentation and type hinting in the future; however, due to limited resources we don't know when it will be ready.
 
Here are some alternatives you can consider:

* [eaglewu/swoole-ide-helper](https://github.com/wudi/swoole-ide-helper)
* [swoft/swoole-ide-helper](https://github.com/swoft-cloud/swoole-ide-helper)

Thanks for reporting it. I have included above information on the repository page (in file README.md), and will leave this issue open (so that other people won't report the same thing if they see it).

**Comment by Kapsonfire** [comment]
How can I help. Is it possible to create a static php file which includes the typehint data like
$typehints = [
    'Coroutine\Mysql::prepare' => '\Swoole\Coroutine\MySQL\Statement'
];

**Comment by deminy** [comment]
Typehints have been added to most classes and functions, and we are keep updating/improving the stubs.

Thanks for submitting the issue and providing suggestions.

Closing the issue.
